version: '2'

networks:
  apix:
    driver: bridge

volumes:
  fcrepo-data: {}
  fuseki-data: {}

services:

  image-java:
    build: docker/java
    image: apix-poc/java
    command: /bin/true

  image-karaf:
    build: docker/karaf
    image: apix-poc/karaf
    depends_on:
      - image-java
    command: /bin/true

  fcrepo:
    build: docker/fcrepo
    image: apix-poc/fcrepo
    depends_on:
      - image-java
    volumes:
      - fcrepo-data:/shared
    networks:
      - apix
    environment:
      - FCREPO_PORT=8983
    ports:
      - "8983:8983"
      - "61613:61613"
      - "61616:61616"

  fuseki:
    build: docker/fuseki
    image: apix-poc/fuseki
    depends_on:
      - image-java
    volumes:
      - fuseki-data:/shared
    networks:
      - apix
    ports:
      - "3030:3030"
    environment:
      - FUSEKI_DEFAULT_DATASET=/fcrepo

  indexing-triplestore:
    build: proof-of-concept/indexing-triplestore
    image: apix-poc/indexing-triplestore
    networks:
      - apix
    depends_on:
      - image-java
    environment:
      - FCREPO_BASEURL=fcrepo:8983/rest
      - JMS_BROKERURL=tcp://fcrepo:61616
      - TRIPLESTORE_BASEURL=fuseki:3030/fcrepo/update
      - ERROR_MAMXREDELIVERIES=100000

  acrepo-apix:
    build: proof-of-concept/amherst-apix/
    image: apix-poc/amherst-apix
    depends_on:
      - image-karaf
    networks:
      - apix
    ports:
      - "13431:13431"
    environment:
      - APIX_REST_HOST=0.0.0.0
      - FCREPO_BASEURL=fcrepo:8983/rest
